function samp=smpte2samp(SMPTE,fps,fs)
%
% QTM 2.16 and higher: Subframe obsolete
%

samp=...
    [SMPTE.Hour]*fs*3600 + ...
    [SMPTE.Minute]*fs*60 + ...
    [SMPTE.Second]*fs + ...
    [SMPTE.Frame]*fs/fps + ...
    [SMPTE.Subframe];